## Load the easyeffects-monitor-volume.lua script (see that file for why)

wireplumber.components = [
  {
    name = easyeffects-monitor-volume.lua, type = script/lua
    provides = custom.easyeffects-monitor-volume
  }
]

wireplumber.profiles = {
  main = {
    custom.easyeffects-monitor-volume = required
  }
}
